### ISSUE TITLE
Добавить еще ингредиенты

### ISSUE THREAD

**Issue by elaman** [rakymbaeva/beauty-box#3]
Сейчас их пять, надо чтобы минимум шесть

**Comment by elaman** [comment]
Не вижу прогресса здесь

**Comment by rakymbaeva** [comment]
мне нужно исправить firebase?

**Comment by elaman** [comment]
Да

**Comment by rakymbaeva** [comment]
но у меня на firebase все работает

**Comment by rakymbaeva** [comment]
как мне исправить подскажите?
